### ISSUE TITLE
Wynik w csv

### ISSUE THREAD

**Issue by ilexpl01** [mlesniew/elicznik#14]
Nie działa mi składnia:

elicznik --format=csv freddy@example.com secretpassword 2024-03-27 > Wynik4.txt

Traceback (most recent call last):
  File "/usr/local/bin/elicznik", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/elicznik/__main__.py", line 68, in main
    for timestamp, consumed, produced in result:
ValueError: too many values to unpack (expected 3)

Co robię źle ?

**Comment by mlesniew** [comment]
To znany problem zgłoszony i naprawiony w #10.

Spróbuj zupgradeować do wersji 2.1.0 z pypi albo prosto z gita.

**Comment by ilexpl01** [comment]
Świeżo zrobione:

root@domoticz:/opt/domoticz/userdata/tauron# pip3 install elicznik
Requirement already satisfied: elicznik in /usr/local/lib/python3.9/dist-packages (2.0.0)
Requirement already satisfied: requests in /usr/local/lib/python3.9/dist-packages (from elicznik) (2.31.0)
Requirement already satisfied: tabulate in /usr/local/lib/python3.9/dist-packages (from elicznik) (0.9.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/dist-packages (from requests->elicznik) (2024.2.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.9/dist-packages (from requests->elicznik) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.9/dist-packages (from requests->elicznik) (2.2.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.9/dist-packages (from requests->elicznik) (3.3.2)

i dalej nie działa :/

**Comment by mlesniew** [comment]
Paczka jest dalej w wersji 2.0.0 zamiast 2.1.0.  Dodaj flagę -U, żeby wymusić upgrade.

**Comment by ilexpl01** [comment]
2024-04-01T00:00:00,0.294,0.0,0.294,0.0
2024-04-01T01:00:00,0.278,0.0,0.278,0.0
2024-04-01T02:00:00,0.312,0.0,0.312,0.0
2024-04-01T03:00:00,0.26,0.0,0.26,0.0
2024-04-01T04:00:00,0.324,0.0,0.324,0.0
2024-04-01T05:00:00,0.258,0.0,0.258,0.0
2024-04-01T06:00:00,0.29,0.0,0.29,0.0
2024-04-01T07:00:00,0.1,0.121,0.0,0.021
2024-04-01T08:00:00,0.0,0.518,0.0,0.518
2024-04-01T09:00:00,0.0,1.664,0.0,1.664
2024-04-01T10:00:00,0.0,2.78,0.0,2.78
2024-04-01T11:00:00,0.0,2.326,0.0,2.326
2024-04-01T12:00:00,0.0,5.587,0.0,5.587
2024-04-01T13:00:00,0.0,6.084,0.0,6.084
2024-04-01T14:00:00,0.0,5.789,0.0,5.789
2024-04-01T15:00:00,0.0,2.32,0.0,2.32
2024-04-01T16:00:00,0.025,0.222,0.0,0.197
2024-04-01T17:00:00,0.34,0.011,0.329,0.0
2024-04-01T18:00:00,0.761,0.0,0.761,0.0
2024-04-01T19:00:00,0.791,0.0,0.791,0.0
2024-04-01T20:00:00,0.452,0.0,0.452,0.0
2024-04-01T21:00:00,0.439,0.0,0.439,0.0
2024-04-01T22:00:00,0.456,0.0,0.456,0.0
2024-04-01T23:00:00,0.362,0.0,0.362,0.0

Pięknie dziękuję :)
